## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1 
  - nightly

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - libgmp-dev

## uncomment the following lines to override the default test script
# script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("ErdosExtras"); Pkg.checkout("Erdos"); Pkg.test("ErdosExtras"; coverage=true)'

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("ErdosExtras")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("ErdosExtras")); include(joinpath("docs", "make.jl"))'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
